const INVALID_ID = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const MONGODB_DUPLICATE_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  INVALID_ID,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  MONGODB_DUPLICATE_ERROR,
  INTERNAL_SERVER_ERROR,
}